### ISSUE TITLE
🐛 [BUG] Unhandled exception. System.ArgumentException: Invalid value '2671030968.9793' for parameter 'interval'.

### ISSUE THREAD

**Issue by binn** [furkandeveloper/EasyCronJob#22]
**Describe the bug**
Not sure what's causing this, but it sometimes happens and sometimes doesn't happen.

**To Reproduce**
Here is the code I used.
![image](https://user-images.githubusercontent.com/25821642/147842594-f6646c7f-59e4-49f4-b78e-7112bf35f0bf.png)
The line in question I believe is the InactiveRemoverService.

Code of AddCronJob
![image](https://user-images.githubusercontent.com/25821642/147842606-5201ce0d-fd71-446a-a593-93a70b6670de.png)

**Expected behavior**
Job scheduled to run every two hours.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 I believe
 - Browser None
 - Version latest

**Comment by binn** [comment]
My bad, it's this line 
`services.AddCronJob<MonthlyRemoverService>("0 0 1 * *");`

Seems to be something wrong with the monthly cron.

**Comment by furkandeveloper** [comment]
Is the issue MonthlyRemoverService.cs or InactiveRemoverService.cs? @binn

**Comment by binn** [comment]
@furkandeveloper sorry forgot to respond, it was MonthlyRemoverService.cs

Scheduling it every month causes this bug to happen for some reason

**Comment by furkandeveloper** [comment]
You're right, this error doesn't happen all the time.

I tried several times on the sample project, but it worked successfully every time.

![image](https://user-images.githubusercontent.com/47147484/149931391-402dee79-392a-460b-adde-d766fdce62b4.png)

I got the same error as you when I used the code below.

```csharp
services.ApplyResulation<ConsoleCronJob>(options =>
{
         options.CronExpression = "* * * 12 *";
         options.TimeZoneInfo = TimeZoneInfo.Local;
});
```

I think the interval value should not be more than 25 days.

I tried the following value as I tried it on 18.01.

I got the same error as it was over 25 days.

```csharp
services.ApplyResulation<ConsoleCronJob>(options =>
{
         options.CronExpression = "* * 13 2 *";
         options.TimeZoneInfo = TimeZoneInfo.Local;
});
```
I didn't get the error when the max was 25 days and the project was successful.

```csharp
services.ApplyResulation<ConsoleCronJob>(options =>
{
         options.CronExpression = "* * 12 2 *";
         options.TimeZoneInfo = TimeZoneInfo.Local;
});
```

Let's summarize;

It uses Timer in EasyCronJob.

Timer cron is used to schedule jobs.

In schedule operations, the current time is subtracted from the time the job will run and is assigned as a delay.

Delay value must not be greater than int.MaxValue.

2671030968.9793 you are getting this error because this value is greater than int.MaxValue.

I guess there is nothing to do. You must use values not greater than int.MaxValue.

**Comment by binn** [comment]
That is pretty weird, pretty faulty limitation. Is there a possible workaround? 
The corn you specified will run once per 25 days, correct? (as in, the 25th of each month or something like that, regardless of the application's state / turn on / turn off)

> In schedule operations, the current time is subtracted from the time the job will run and is assigned as a delay.
Delay value must not be greater than int.MaxValue.

Timer, being limited to an integer, may not be suitable then. Any other suggestions or patterns that may work out for the library?

**Comment by furkandeveloper** [comment]
I prepared a solution for you.

This solution contains Overengineering methods.

### Startup.cs

```csharp
services.ApplyResulation<YourCronJob>(options =>
{
    options.CronExpression = "0 0 25 * *";
    options.TimeZoneInfo = TimeZoneInfo.Local;
});
```

### YourCronJob.cs

```csharp
public class YourCronJob : CronJobService
{
    private System.Timers.Timer timer;
    private readonly ILogger<YourCronJob> logger;
    public YourCronJob(ICronConfiguration<YourCronJob> cronConfiguration, ILogger<YourCronJob> logger)
        : base(cronConfiguration.CronExpression, cronConfiguration.TimeZoneInfo)
    {
        this.logger = logger;
    }
    private TimeSpan CalculateTimerDelay()
    {
        DateTime next = new DateTime(DateTime.Now.Year, DateTime.Now.AddMonths(1).Month, 1);
        var delay = next - DateTimeOffset.Now;
        return delay;
    }
    public override Task StartAsync(CancellationToken cancellationToken)
    {
        var delay = CalculateTimerDelay();
        timer = new System.Timers.Timer(delay.TotalMilliseconds);
        logger.LogInformation("Start Your Job" + " Start Time : " + DateTime.UtcNow);
        return base.StartAsync(cancellationToken);
    }
    protected override Task ScheduleJob(CancellationToken cancellationToken)
    {
        logger.LogInformation("Schedule Your Job" + " Start Time : " + DateTime.UtcNow);
        return base.ScheduleJob(cancellationToken);
    }
    public override Task DoWork(CancellationToken cancellationToken)
    {
        logger.LogInformation("Timer Starting" + " Start Time : " + DateTime.UtcNow);
        timer.Elapsed += async (sender, args) =>
        {
            timer.Dispose();  // reset and dispose timer
            timer = null;
            Test();
        };
        timer.Start();
        return base.DoWork(cancellationToken);
    }
    public void Test()
    {
        var delay = CalculateTimerDelay();
        timer = new System.Timers.Timer(delay.TotalMilliseconds);
        logger.LogInformation("Working Your Job" + " Start Time : " + DateTime.UtcNow);
    }
}
```

### Result

It will run on the 25th day of each month and create a timer until the first day of the next month.

So the int.MaxValue limit will not block you.

fyi @binn

**Comment by enisn** [comment]
It's kinda workaround and seems like a good approach to get over the problem. Thanks @furkandeveloper

**Comment by binn** [comment]
Thank you, I'll try it out in the coming days.

**Comment by Alchoder** [comment]
Hello, I got the same problem. Maybe to fix this you could something else than System.Timers.Timer ? 

Maybe System.Threading.Timer or 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/45818215/229478910-9c01bd00-a998-4480-8aa1-53be6c56c1b0.png">

https://stackoverflow.com/questions/41284103/assign-a-double-value-to-timer-interval
https://stackoverflow.com/questions/34047810/timer-max-interval

**Comment by Alchoder** [comment]
Not sure this will work, let me know about it.

```
    public class MyJob: AbstractCronJobService<CronJobGenerationFacturesCommandes>
    {
        private readonly ILogger<MyJob> _logger;
        private System.Timers.Timer timer;

        public MyJob(ICronConfiguration<MyJob> cronConfiguration,
                                        ILogger<MyJob> logger,
                                        IServiceProvider serviceProvider) :
            base(cronConfiguration, logger, serviceProvider)
        {
            _logger = logger;
        }

        public void DoJob()
        {
            _logger.LogInformation($"DoJob - {CronName}");

            //Code of what my job is supposed to do
        }

        public override Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Delayed Start [{CronName}]");
            return base.StartAsync(cancellationToken);
        }

        protected override Task ScheduleJob(CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Custom Schedule {CronName}");
            return base.ScheduleJob(cancellationToken);
        }

        public override Task DoWork(CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Delayed Timer Starting - {CronName}");
            var delay = CalculateTimerDelay();
            timer = new System.Timers.Timer(delay.TotalMilliseconds);

            timer.Elapsed += (sender, args) =>
            {
                //Reset and dispose timer
                timer.Dispose();
                timer = null;
                DoJob();
            };
            timer.Start();

            return base.DoWork(cancellationToken);
        }

        private TimeSpan CalculateTimerDelay()
        {
            DateTime next = new DateTime(DateTime.Now.Year, DateTime.Now.AddMonths(1).Month, 1);
            var delay = next - DateTimeOffset.Now;
            return delay;
        }

    }

```

**Comment by furkandeveloper** [comment]
Hello,
First of all, thank you for the detailed explanation.
Timer works with maximum int.MaxValue.
Therefore, some errors occur in such problems.
We've developed the solution you referenced above as a workaround.
Of course they may have mistakes.
The example implementation you shared seems to be correct.
DoWork is the part that will work for the cron job.
Here, when the time is up, resetting the timer object and re-defining a job may be the solution.
Please share the result with us at the end of the month.
If your implementation works correctly, we will add your solution to the Wiki section.

@Alchoder

**Comment by Alchoder** [comment]
Hello @furkandeveloper,

You're welcome :)

I understand.

I'll try to remember to let you know :)

**Comment by Alchoder** [comment]
Hello, 

It worked well for me :)

**Comment by Alchoder** [comment]
Actually it did not work completely.
I replaced
```
services.ApplyResulation<MyJob>(options =>
{
    options.CronExpression = "0 0 15,25 * *";
    options.TimeZoneInfo = TimeZoneInfo.Local;
});
```

by

```
services.ApplyResulation<MyJob>(options =>
{
    options.CronExpression = "0 23 15,28,29,30,31 * *";
    options.TimeZoneInfo = TimeZoneInfo.Local;
});
```

Indeed, when the server was rebooting between the 25th and the end of the month, it could not compute the time when it should be launched. 
With this new cron expression, it is launched every last day of month at 11P.M. Unfortunately, the way i wrote it, if the server reboots between 11P.M. and midnight, it won't work. I did set to 11:59 P.M. because I have treatments to make at 11:30.
Anyway, it should work 99,99% of time

**Comment by sergevic** [comment]
I have a similar/related issue, but with negative value, passed to the Timer constructor.

```
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Invalid value '-0.0001' for parameter 'interval'.
   at System.Timers.Timer..ctor(Double interval)
   at EasyCronJob.Abstractions.CronJobService.ScheduleJob(CancellationToken cancellationToken)
   at EasyCronJob.Abstractions.CronJobService.<>c__DisplayClass5_0.<<ScheduleJob>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

My cron is "*/5 * * * *". I can see that the error happens periodically (~ once per day) but always when time has 0 seconds. I.e at 11:45:00, 21:40:00, 11:55:00.

As I can see from the source code `ScheduleJob` function [checks](https://github.com/furkandeveloper/EasyCronJob/blob/2fbb4fd53a419a6f66939400fe6a538bc08a5190/src/EasyCronJob.Abstractions/CronJobService.cs#L34) for negative values, but do not return after the recursive call

```
if (delay.TotalMilliseconds <= 0)   // prevent non-positive values from being passed into Timer
{
    await ScheduleJob(cancellationToken).ConfigureAwait(true); 
}
timer = new System.Timers.Timer(delay.TotalMilliseconds);   <--- here it is negative
```
