### ISSUE TITLE
Have the ICronConfiguration load from the appsettings ✨ [FEATURE]

### ISSUE THREAD

**Issue by henzard** [furkandeveloper/EasyCronJob#23]
## Summary
It would be really helpful to load the ICronConfiguration for the appsettings.
 
## Advantage
Services can be updated without recompiling 

**Additional context**
Maybe consider 
```
{
     "CronConfiguration" : [
            "ServiceName" {
                    "CronExpression": "*/10 * * * * *",
                    "TimeZoneInfo": "Local"
             }
      ]
}
````

**Comment by furkandeveloper** [comment]
Hello again,

I have developed a new package for your request.

You can find the details of the package and the user manual on the wiki page below.

Thanks for your contribution.

https://github.com/furkandeveloper/EasyCronJob/wiki/AutoConfiguration
