### ISSUE TITLE
✨ [FEATURE] Add the ability to specify seconds in cron expressions

### ISSUE THREAD

**Issue by Helmoz** [furkandeveloper/EasyCronJob#25]
## Summary
Hi! Can you please add the ability to specify seconds in cron expression? Need to run a task every 10 seconds.

**Additional context**
I saw that for parsing expressions you used Cronos, and in its Parse method there is an overload for include seconds
`CronExpression expression = CronExpression.Parse("*/10 * * * * *", CronFormat.IncludeSeconds);`

**Comment by furkandeveloper** [comment]
Hi,

Thanks for your contribution.

Added to TODO list. I will review it and include it in the development process.

fyi @Helmoz

**Comment by furkandeveloper** [comment]
Hello again,

You must use version 2.1.0 to use this feature.

Review the wiki document again and see how the cronformat setting is set in your Startup.cs and Cron jobs.

fyi @Helmoz
