### ISSUE TITLE
How to use any thread

### ISSUE THREAD

**Issue by saiid2020** [furkandeveloper/EasyCronJob#29]
public class CronJobUpdateVisitorVisitDay:CronJobService
    {
        private readonly ApplicationDbContext _ApplicationDbContext;
        private readonly UserManager<ApplicationUser> _UserManager;

        public CronJobUpdateVisitorVisitDay(ICronConfiguration<CronJobUpdateVisitorVisitDay> cronConfiguration, ApplicationDbContext applicationDbContext,UserManager<ApplicationUser> userManager) 
            : base(cronConfiguration.CronExpression,cronConfiguration.TimeZoneInfo,cronConfiguration.CronFormat)
        {
            _ApplicationDbContext = applicationDbContext;
            _UserManager = userManager;
        }
        protected override async Task ScheduleJob(CancellationToken cancellationToken)
        {
            await CustomExtension.StoreVisitorVisitDay(_ApplicationDbContext, _UserManager);
            await base.ScheduleJob(cancellationToken);

        }

        
        public override async Task StartAsync(CancellationToken cancellationToken)
        {
            await CustomExtension.StoreVisitorVisitDay(_ApplicationDbContext, _UserManager);
            await base.StartAsync(cancellationToken);

        }

     
    }
In this code, StartAsync and ScheduleJob are run consecutively, while according to the settings, they must be run every 25 minutes every hour.

    services.ApplyResulation<CronJobUpdateVisitorVisitDay>(options =>
            {
                options.CronExpression = "25 * * * *";
                options.TimeZoneInfo = TimeZoneInfo.Local;
                options.CronFormat = Cronos.CronFormat.Standard;
            });

**Comment by furkandeveloper** [comment]
StartAsync creates and sets up the defined job.

ScheduleAsync sets the next run time.

DoWork contains the logic that the defined job will run.

So you should write your logic in DoWork.

You can clone the project and examine the sample project.

fyi @saiid2020

**Comment by saiid2020** [comment]
Thanks for the help, my problem was solved
